<?php

namespace suframe\thinkAdmin\controller;

use think\facade\View;

abstract class Base extends BaseController
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setViewPath();
    }

    protected function setViewPath()
    {
        if(!$this->request->isAjax()){
            View::config(['view_path' => __DIR__ . '/../view/']);
        }
    }

}
